ALTER SESSION SET NLS_LANGUAGE= 'american';

CREATE TABLESPACE project_ts
    DATAFILE 'project_ts.dbf'
    SIZE 7 m
    AUTOEXTEND ON NEXT 5 m
    MAXSIZE 100 m;                                                                                             
SELECT * FROM USER_SYS_PRIVS;
--DROP TABLESPACE project_ts;

CREATE TEMPORARY TABLESPACE project_ts_temp
    TEMPFILE 'project_ts_temp.dbf'
    SIZE 5 m
    AUTOEXTEND ON NEXT 5 m
    MAXSIZE 100 m;
--DROP TABLESPACE project_ts_temp;

SELECT * FROM dba_tablespaces;

------------------------ [ROLES]------------------------

--DROP ROLE Admin_Role;
CREATE ROLE Admin_Role;
GRANT CREATE SESSION TO Admin_Role;

GRANT EXECUTE ON DEVELOPER.admin_package to Admin_role;

--DROP ROLE Buyer_Role;
CREATE ROLE Buyer_Role;
GRANT CREATE SESSION TO Buyer_Role;

GRANT EXECUTE ON DEVELOPER.buyer_package to Buyer_role;

--DROP ROLE Seller_Role;
CREATE ROLE Seller_Role;
GRANT CREATE SESSION TO Seller_Role;

GRANT EXECUTE ON DEVELOPER.seller_package to Seller_role;

------------------------ [PROFILES] ------------------------
--DROP PROFILE Core_Profile cascade;
CREATE PROFILE Core_Profile LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 60;

--DROP PROFILE Buyer_Profile CASCADE;
CREATE PROFILE Buyer_Profile LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 100
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 60;

--DROP PROFILE Seller_Profile CASCADE;
CREATE PROFILE Seller_Profile LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 60
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 60;

SELECT * FROM dba_profiles WHERE profile LIKE '%';

------------------------ [USERS] ------------------------
--DROP USER Admin_User
CREATE USER Admin_User IDENTIFIED BY root
DEFAULT TABLESPACE project_ts
QUOTA UNLIMITED ON project_ts
TEMPORARY TABLESPACE project_ts_temp
PROFILE Core_Profile
ACCOUNT UNLOCK;

--DROP USER Buyer_User
CREATE USER Buyer_User IDENTIFIED BY "12345"
DEFAULT TABLESPACE project_ts QUOTA UNLIMITED ON project_ts
TEMPORARY TABLESPACE project_ts_temp
PROFILE Buyer_Profile
ACCOUNT UNLOCK;

--DROP USER Seller_User
CREATE USER Seller_User IDENTIFIED BY "12345"
DEFAULT TABLESPACE project_ts QUOTA UNLIMITED ON project_ts
TEMPORARY TABLESPACE project_ts_temp
PROFILE Seller_Profile
ACCOUNT UNLOCK;

SELECT * FROM user_objects;

GRANT Admin_Role TO Admin_User;

GRANT Buyer_Role TO Buyer_User;

GRANT Seller_Role TO Seller_User;

------------------------ [TABLES] ------------------------

CREATE TABLE Users
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email VARCHAR2(255) UNIQUE NOT NULL,
	password VARCHAR2(255) NOT NULL,
	username VARCHAR2(255) NOT NULL,
	role_id NUMBER,
	account INT DEFAULT 0
)TABLESPACE project_ts;

CREATE TABLE Item (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR2(255) NOT NULL,
	description VARCHAR2(255) NOT NULL,
	userId INT NOT NULL,
	endTime DATE,
	startPrice INT NOT NULL,
	winnerPrice INT DEFAULT 0,
	typeId INT NOT NULL
)TABLESPACE project_ts;

ALTER TABLE Item ADD buyerId INT DEFAULT NULL;
ALTER TABLE Users MODIFY Id GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE Item ADD CONSTRAINT Item_fk2 FOREIGN KEY (buyerId) REFERENCES Users(id);
ALTER TABLE Item MODIFY buyerId DEFAULT 0;

CREATE TABLE Category (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR2(255) NOT NULL
)TABLESPACE project_ts;


CREATE TABLE ItemsCategory (
    id INT PRIMARY KEY,
	itemId INT NOT NULL ,
	categoryId INT NOT NULL
)TABLESPACE project_ts;

ALTER TABLE ItemsCategory ADD CONSTRAINT constr UNIQUE(itemId, categoryId);

Create Table Auction (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	categoryId INT,
	startDate DATE NOT NULL
)TABLESPACE project_ts;

CREATE TABLE AuctionType (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR2(255) NOT NULL
)TABLESPACE project_ts;

CREATE TABLE ItemsAuction (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	itemId INT NOT NULL,
	auctionId INT NOT NULL,
	count INT NOT NULL
)TABLESPACE project_ts;

CREATE TABLE Roles (
    roleId NUMBER GENERATED ALWAYS AS IDENTITY,
    roleName VARCHAR(20),
    CONSTRAINT roles_PK PRIMARY KEY(roleId)
)TABLESPACE project_ts;

ALTER TABLE Item ADD CONSTRAINT Item_fk0 FOREIGN KEY (userId) REFERENCES Users(id);
ALTER TABLE Item ADD CONSTRAINT Item_fk1 FOREIGN KEY  (typeId) REFERENCES AuctionType(id) ;

ALTER TABLE ItemsCategory ADD CONSTRAINT ItemsCategory_fk0 FOREIGN KEY (itemId) REFERENCES Item(id);
ALTER TABLE ItemsCategory ADD CONSTRAINT ItemsCategory_fk1 FOREIGN KEY (categoryId) REFERENCES Category(id);

ALTER TABLE Auction ADD CONSTRAINT Auction_fk0 FOREIGN KEY (categoryId) REFERENCES Category(id);

ALTER TABLE ItemsAuction ADD CONSTRAINT ItemsAuction_fk0 FOREIGN KEY (itemId) REFERENCES Item(id);
ALTER TABLE ItemsAuction ADD CONSTRAINT ItemsAuction_fk1 FOREIGN KEY (auctionId) REFERENCES Auction(id);

ALTER TABLE Users ADD CONSTRAINT users_FK_to_roles FOREIGN KEY (role_id) REFERENCES roles(roleId);

CREATE TABLE Notifications
(
    id             number generated by default as identity primary key,
    operation_date date not null,
    message        varchar2(1000),
    user_id        number,
    is_read        number default 0,
    constraint notification_pk foreign key (user_id) references users (id)
);

DROP TABLE ItemsAuction;
DROP TABLE Auction;
DROP TABLE ItemsCategory;
DROP TABLE Category;
DROP TABLE Item;
DROP TABLE AuctionType;
DROP TABLE Notifications;
DROP TABLE Users;
DROP TABLE Roles;