ALTER SESSION SET NLS_LANGUAGE= 'american';

CREATE TABLESPACE project_ts
    DATAFILE 'project_ts.dbf'
    SIZE 7 m
    AUTOEXTEND ON NEXT 5 m
    MAXSIZE 100 m;                                                                                             
    
--DROP TABLESPACE project_ts;

CREATE TEMPORARY TABLESPACE project_ts_temp
    TEMPFILE 'project_ts_temp.dbf'
    SIZE 5 m
    AUTOEXTEND ON NEXT 5 m
    MAXSIZE 100 m;
    
--DROP TABLESPACE project_ts_temp;

SELECT * FROM dba_tablespaces;

------------------------ [ROLES]------------------------

--DROP ROLE Admin_Role;
CREATE ROLE Admin_Role;

GRANT CREATE SESSION, CONNECT TO Admin_Role;

--DROP ROLE Buyer_Role;
CREATE ROLE Buyer_Role;

GRANT CREATE SESSION, CONNECT TO Buyer_Role;

--DROP ROLE Seller_Role;
CREATE ROLE Seller_Role;

GRANT CREATE SESSION, CONNECT TO Seller_Role;

------------------------ [PROFILES] ------------------------
--DROP PROFILE Core_Profile;
CREATE PROFILE Core_Profile LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 60;

--DROP PROFILE Buyer_Profile;
CREATE PROFILE Buyer_Profile LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 100
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 60;

--DROP PROFILE Seller_Profile;
CREATE PROFILE Seller_Profile LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 60
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_LOCK_TIME 1
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 60;

SELECT * FROM dba_profiles WHERE profile LIKE '%';

------------------------ [USERS] ------------------------
--DROP USER Admin_User
CREATE USER Admin_User IDENTIFIED BY root
DEFAULT TABLESPACE project_ts QUOTA UNLIMITED ON project_ts
TEMPORARY TABLESPACE project_ts_temp
PROFILE Core_Profile
ACCOUNT UNLOCK;

--DROP USER Buyer_User
CREATE USER Buyer_User IDENTIFIED BY "12345"
DEFAULT TABLESPACE project_ts QUOTA 100 m ON project_ts
TEMPORARY TABLESPACE project_ts_temp
PROFILE Buyer_Profile
ACCOUNT UNLOCK;

--DROP USER Seller_User
CREATE USER Seller_User IDENTIFIED BY "12345"
DEFAULT TABLESPACE project_ts QUOTA 100 m ON project_ts
TEMPORARY TABLESPACE project_ts_temp
PROFILE Seller_Profile
ACCOUNT UNLOCK;

CREATE USER absolute_user IDENTIFIED BY "12345"
DEFAULT TABLESPACE project_ts QUOTA 100 m ON project_ts
TEMPORARY TABLESPACE project_ts_temp
ACCOUNT UNLOCK;

GRANT ALL PRIVILEGES
TO absolute_user;

GRANT EXECUTE ON dbms_crypto TO absolute_user;

SELECT * FROM user_objects;

GRANT EXECUTE ON absolute_user.signup_procedure TO public;
GRANT EXECUTE ON signin_procedure TO public;

GRANT Admin_Role TO Admin_User;

--TODO GRANT EXECUTE

GRANT Buyer_Role TO Buyer_User;

--TODO GRANT EXECUTE

GRANT Seller_Role TO Seller_User;

--TODO GRANT EXECUTE

------------------------ [TABLES] ------------------------

CREATE TABLE Users
(
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	email VARCHAR2(255) UNIQUE NOT NULL,
	password VARCHAR2(255) NOT NULL,
	username VARCHAR(255) NOT NULL,
	role_id NUMBER,
	account Int Default 0
)TABLESPACE project_ts;
/

CREATE TABLE Item (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR2(255) NOT NULL,
	description VARCHAR2(255) NOT NULL,
	userId INT NOT NULL,
	endTime DATE,
	startPrice INT NOT NULL,
	winnerPrice INT DEFAULT 0,
	typeId INT NOT NULL
)TABLESPACE project_ts;

Alter Table Item
add buyerId int default NULL;

Alter Table Users
Modify Id Generated By Default As Identity;

ALTER TABLE Item ADD CONSTRAINT Item_fk2 FOREIGN KEY (buyerId) REFERENCES Users(id);
/
CREATE TABLE Category (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR2(255) NOT NULL
)TABLESPACE project_ts;
/

CREATE TABLE ItemsCategory (
	itemId INT NOT NULL,
	categoryId INT NOT NULL
)TABLESPACE project_ts;

alter table ItemsCategory add constraint constr unique(itemId, categoryId);
/

Create Table Auction (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	categoryId INT,
	startDate DATE NOT NULL
)TABLESPACE project_ts;
/

CREATE TABLE AuctionType (
	id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	title VARCHAR2(255) NOT NULL
)TABLESPACE project_ts;
/

CREATE TABLE ItemsAuction (
	itemId INT NOT NULL,
	auctionId INT NOT NULL,
	count INT NOT NULL
)TABLESPACE project_ts;
/

CREATE TABLE Roles (
    role_id NUMBER GENERATED ALWAYS AS IDENTITY,
    role_name VARCHAR(20),
    CONSTRAINT roles_PK PRIMARY KEY(role_id)
)TABLESPACE project_ts;
/

ALTER TABLE Item ADD CONSTRAINT Item_fk0 FOREIGN KEY (userId) REFERENCES Users(id);
ALTER TABLE Item ADD CONSTRAINT Item_fk1 FOREIGN KEY (typeId) REFERENCES AuctionType(id);

ALTER TABLE ItemsCategory ADD CONSTRAINT ItemsCategory_fk0 FOREIGN KEY (itemId) REFERENCES Item(id);
ALTER TABLE ItemsCategory ADD CONSTRAINT ItemsCategory_fk1 FOREIGN KEY (categoryId) REFERENCES Category(id);

ALTER TABLE Auction ADD CONSTRAINT Auction_fk0 FOREIGN KEY (categoryId) REFERENCES Category(id);

ALTER TABLE ItemsAuction ADD CONSTRAINT ItemsAuction_fk0 FOREIGN KEY (itemId) REFERENCES Item(id);
ALTER TABLE ItemsAuction ADD CONSTRAINT ItemsAuction_fk1 FOREIGN KEY (auctionId) REFERENCES Auction(id);

ALTER TABLE Users ADD CONSTRAINT users_FK_to_roles FOREIGN KEY (role_id) REFERENCES roles(role_id);

DROP TABLE ItemsAuction;
DROP TABLE Auction;
DROP TABLE ItemsCategory;
DROP TABLE Category;
DROP TABLE Item;
DROP TABLE AuctionType;
DROP TABLE Users;
DROP TABLE Roles;

SELECT * FROM user_tables WHERE tablespace_name = 'PROJECT_TS'